 const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

 const DRAGON = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
};

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_DRAGONS = {
    FETCH: 'ACCOUNT_DRAGONS_FETCH',
    FETCH_ERROR: 'ACCOUNT_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_DRAGONS_FETCH_SUCCESS'
};

const ACCOUNT_INFO = {
    FETCH: 'ACCOUNT_INFO_FETCH',
    FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
};

const PUBLIC_DRAGONS = {
    FETCH: 'PUBLIC_DRAGONS_FETCH',
    FETCH_ERROR: 'PUBLIC_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_DRAGONS_FETCH_SUCCESS'
};

const POPULAR_DRAGONS = {
    FETCH: 'POPULAR_DRAGONS_FETCH',
    FETCH_ERROR: 'POPULAR_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS: 'POPULAR_DRAGONS_FETCH_SUCCESS'
};

const SEARCH = {
    FETCH: 'SEARCH_FETCH',
    FETCH_ERROR: 'SEARCH_FETCH_ERROR',
    FETCH_SUCCESS: 'SEARCH_FETCH_SUCCESS'
};

const SEARCH_SORT = {
    FETCH: 'SEARCH_SORT_FETCH',
    FETCH_ERROR: 'SEARCH_SORT_FETCH_ERROR',
    FETCH_SUCCESS: 'SEARCH_SORT_FETCH_SUCCESS'
};

const SEARCH_FILTER_CHECK = {
    FETCH: 'SEARCH_FILTER_CHECK_FETCH',
    FETCH_ERROR: 'SEARCH_FILTER_CHECK_FETCH_ERROR',
    FETCH_SUCCESS: 'SEARCH_FILTER_CHECK_SUCCESS'
};

const SEARCH_FILTER_RANGE = {
    FETCH: 'SEARCH_FILTER_RANGE_FETCH',
    FETCH_ERROR: 'SEARCH_FILTER_RANGE_FETCH_ERROR',
    FETCH_SUCCESS: 'SEARCH_FILTER_RANGE_SUCCESS'
};

const SEARCH_CURRENT_PAGE = {
    FETCH: 'SEARCH_CURRENT_PAGE_FETCH',
    FETCH_ERROR: 'SEARCH_CURRENT_PAGE_ERROR',
    FETCH_SUCCESS: 'SEARCH_CURRENT_PAGE_SUCCESS'
};

export {
    GENERATION,
    DRAGON, 
    ACCOUNT, 
    ACCOUNT_DRAGONS, 
    ACCOUNT_INFO, 
    PUBLIC_DRAGONS,
    SEARCH, 
    SEARCH_SORT, 
    SEARCH_FILTER_CHECK, 
    SEARCH_FILTER_RANGE, 
    POPULAR_DRAGONS,
    SEARCH_CURRENT_PAGE
};